/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddPerformanceInput {
  'teamA' : string,
  'teamB' : string,
  'date' : Timestamp,
  'playerId' : PlayerId,
  'runs' : bigint,
  'matchId' : MatchId,
  'wickets' : bigint,
}
export interface CreatePlayerInput {
  'country' : string,
  'name' : string,
  'role' : PlayerRole,
}
export interface LeaderboardEntry {
  'player' : PlayerSummary,
  'rank' : bigint,
  'statValue' : number,
}
export type LeaderboardType = { 'runs' : null } |
  { 'average' : null } |
  { 'wickets' : null };
export type MatchId = string;
export type PerformanceId = string;
export interface PerformanceSummary {
  'date' : Timestamp,
  'runs' : bigint,
  'matchId' : MatchId,
  'wickets' : bigint,
}
export interface PlayerDetail {
  'id' : PlayerId,
  'country' : string,
  'matchCount' : bigint,
  'totalWickets' : bigint,
  'name' : string,
  'role' : PlayerRole,
  'average' : number,
  'last5Performances' : Array<PerformanceSummary>,
  'totalRuns' : bigint,
  'strikeRate' : number,
}
export type PlayerId = string;
export type PlayerRole = { 'allRounder' : null } |
  { 'batter' : null } |
  { 'bowler' : null };
export interface PlayerSummary {
  'id' : PlayerId,
  'country' : string,
  'matchCount' : bigint,
  'totalWickets' : bigint,
  'name' : string,
  'role' : PlayerRole,
  'totalRuns' : bigint,
}
export type Timestamp = bigint;
export interface UpdatePlayerInput {
  'country' : [] | [string],
  'name' : [] | [string],
  'role' : [] | [PlayerRole],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addPerformance' : ActorMethod<[AddPerformanceInput], PerformanceId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlayer' : ActorMethod<[CreatePlayerInput], PlayerId>,
  'deletePlayer' : ActorMethod<[PlayerId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[LeaderboardType], Array<LeaderboardEntry>>,
  'getPlayer' : ActorMethod<[PlayerId], [] | [PlayerDetail]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPlayers' : ActorMethod<[], Array<PlayerSummary>>,
  'updatePlayer' : ActorMethod<[PlayerId, UpdatePlayerInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];