/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const PlayerId = IDL.Text;
export const MatchId = IDL.Text;
export const AddPerformanceInput = IDL.Record({
  'teamA' : IDL.Text,
  'teamB' : IDL.Text,
  'date' : Timestamp,
  'playerId' : PlayerId,
  'runs' : IDL.Nat,
  'matchId' : MatchId,
  'wickets' : IDL.Nat,
});
export const PerformanceId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlayerRole = IDL.Variant({
  'allRounder' : IDL.Null,
  'batter' : IDL.Null,
  'bowler' : IDL.Null,
});
export const CreatePlayerInput = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'role' : PlayerRole,
});
export const LeaderboardType = IDL.Variant({
  'runs' : IDL.Null,
  'average' : IDL.Null,
  'wickets' : IDL.Null,
});
export const PlayerSummary = IDL.Record({
  'id' : PlayerId,
  'country' : IDL.Text,
  'matchCount' : IDL.Nat,
  'totalWickets' : IDL.Nat,
  'name' : IDL.Text,
  'role' : PlayerRole,
  'totalRuns' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'player' : PlayerSummary,
  'rank' : IDL.Nat,
  'statValue' : IDL.Float64,
});
export const PerformanceSummary = IDL.Record({
  'date' : Timestamp,
  'runs' : IDL.Nat,
  'matchId' : MatchId,
  'wickets' : IDL.Nat,
});
export const PlayerDetail = IDL.Record({
  'id' : PlayerId,
  'country' : IDL.Text,
  'matchCount' : IDL.Nat,
  'totalWickets' : IDL.Nat,
  'name' : IDL.Text,
  'role' : PlayerRole,
  'average' : IDL.Float64,
  'last5Performances' : IDL.Vec(PerformanceSummary),
  'totalRuns' : IDL.Nat,
  'strikeRate' : IDL.Float64,
});
export const UpdatePlayerInput = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'role' : IDL.Opt(PlayerRole),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addPerformance' : IDL.Func([AddPerformanceInput], [PerformanceId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlayer' : IDL.Func([CreatePlayerInput], [PlayerId], []),
  'deletePlayer' : IDL.Func([PlayerId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [LeaderboardType],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(PlayerDetail)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPlayers' : IDL.Func([], [IDL.Vec(PlayerSummary)], ['query']),
  'updatePlayer' : IDL.Func([PlayerId, UpdatePlayerInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const PlayerId = IDL.Text;
  const MatchId = IDL.Text;
  const AddPerformanceInput = IDL.Record({
    'teamA' : IDL.Text,
    'teamB' : IDL.Text,
    'date' : Timestamp,
    'playerId' : PlayerId,
    'runs' : IDL.Nat,
    'matchId' : MatchId,
    'wickets' : IDL.Nat,
  });
  const PerformanceId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlayerRole = IDL.Variant({
    'allRounder' : IDL.Null,
    'batter' : IDL.Null,
    'bowler' : IDL.Null,
  });
  const CreatePlayerInput = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'role' : PlayerRole,
  });
  const LeaderboardType = IDL.Variant({
    'runs' : IDL.Null,
    'average' : IDL.Null,
    'wickets' : IDL.Null,
  });
  const PlayerSummary = IDL.Record({
    'id' : PlayerId,
    'country' : IDL.Text,
    'matchCount' : IDL.Nat,
    'totalWickets' : IDL.Nat,
    'name' : IDL.Text,
    'role' : PlayerRole,
    'totalRuns' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'player' : PlayerSummary,
    'rank' : IDL.Nat,
    'statValue' : IDL.Float64,
  });
  const PerformanceSummary = IDL.Record({
    'date' : Timestamp,
    'runs' : IDL.Nat,
    'matchId' : MatchId,
    'wickets' : IDL.Nat,
  });
  const PlayerDetail = IDL.Record({
    'id' : PlayerId,
    'country' : IDL.Text,
    'matchCount' : IDL.Nat,
    'totalWickets' : IDL.Nat,
    'name' : IDL.Text,
    'role' : PlayerRole,
    'average' : IDL.Float64,
    'last5Performances' : IDL.Vec(PerformanceSummary),
    'totalRuns' : IDL.Nat,
    'strikeRate' : IDL.Float64,
  });
  const UpdatePlayerInput = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'role' : IDL.Opt(PlayerRole),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addPerformance' : IDL.Func([AddPerformanceInput], [PerformanceId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlayer' : IDL.Func([CreatePlayerInput], [PlayerId], []),
    'deletePlayer' : IDL.Func([PlayerId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [LeaderboardType],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(PlayerDetail)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPlayers' : IDL.Func([], [IDL.Vec(PlayerSummary)], ['query']),
    'updatePlayer' : IDL.Func([PlayerId, UpdatePlayerInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };