/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    player: PlayerSummary;
    rank: bigint;
    statValue: number;
}
export type Timestamp = bigint;
export type MatchId = string;
export type PerformanceId = string;
export type PlayerId = string;
export interface CreatePlayerInput {
    country: string;
    name: string;
    role: PlayerRole;
}
export interface PerformanceSummary {
    date: Timestamp;
    runs: bigint;
    matchId: MatchId;
    wickets: bigint;
}
export interface UpdatePlayerInput {
    country?: string;
    name?: string;
    role?: PlayerRole;
}
export interface PlayerDetail {
    id: PlayerId;
    country: string;
    matchCount: bigint;
    totalWickets: bigint;
    name: string;
    role: PlayerRole;
    average: number;
    last5Performances: Array<PerformanceSummary>;
    totalRuns: bigint;
    strikeRate: number;
}
export interface PlayerSummary {
    id: PlayerId;
    country: string;
    matchCount: bigint;
    totalWickets: bigint;
    name: string;
    role: PlayerRole;
    totalRuns: bigint;
}
export interface AddPerformanceInput {
    teamA: string;
    teamB: string;
    date: Timestamp;
    playerId: PlayerId;
    runs: bigint;
    matchId: MatchId;
    wickets: bigint;
}
export enum LeaderboardType {
    runs = "runs",
    average = "average",
    wickets = "wickets"
}
export enum PlayerRole {
    allRounder = "allRounder",
    batter = "batter",
    bowler = "bowler"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addPerformance(input: AddPerformanceInput): Promise<PerformanceId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPlayer(input: CreatePlayerInput): Promise<PlayerId>;
    deletePlayer(playerId: PlayerId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(leaderboardType: LeaderboardType): Promise<Array<LeaderboardEntry>>;
    getPlayer(playerId: PlayerId): Promise<PlayerDetail | null>;
    isCallerAdmin(): Promise<boolean>;
    listPlayers(): Promise<Array<PlayerSummary>>;
    updatePlayer(playerId: PlayerId, input: UpdatePlayerInput): Promise<boolean>;
}
import type { CreatePlayerInput as _CreatePlayerInput, LeaderboardEntry as _LeaderboardEntry, LeaderboardType as _LeaderboardType, PerformanceSummary as _PerformanceSummary, PlayerDetail as _PlayerDetail, PlayerId as _PlayerId, PlayerRole as _PlayerRole, PlayerSummary as _PlayerSummary, UpdatePlayerInput as _UpdatePlayerInput, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addPerformance(arg0: AddPerformanceInput): Promise<PerformanceId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPerformance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPerformance(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPlayer(arg0: CreatePlayerInput): Promise<PlayerId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(to_candid_CreatePlayerInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(to_candid_CreatePlayerInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deletePlayer(arg0: PlayerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: LeaderboardType): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_LeaderboardType_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_LeaderboardType_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: PlayerId): Promise<PlayerDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPlayers(): Promise<Array<PlayerSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlayers();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlayers();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlayer(arg0: PlayerId, arg1: UpdatePlayerInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, to_candid_UpdatePlayerInput_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, to_candid_UpdatePlayerInput_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_LeaderboardEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerDetail_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerDetail): PlayerDetail {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerRole): PlayerRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerSummary_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerSummary): PlayerSummary {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerDetail]): PlayerDetail | null {
    return value.length === 0 ? null : from_candid_PlayerDetail_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    player: _PlayerSummary;
    rank: bigint;
    statValue: number;
}): {
    player: PlayerSummary;
    rank: bigint;
    statValue: number;
} {
    return {
        player: from_candid_PlayerSummary_n14(_uploadFile, _downloadFile, value.player),
        rank: value.rank,
        statValue: value.statValue
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    country: string;
    matchCount: bigint;
    totalWickets: bigint;
    name: string;
    role: _PlayerRole;
    totalRuns: bigint;
}): {
    id: PlayerId;
    country: string;
    matchCount: bigint;
    totalWickets: bigint;
    name: string;
    role: PlayerRole;
    totalRuns: bigint;
} {
    return {
        id: value.id,
        country: value.country,
        matchCount: value.matchCount,
        totalWickets: value.totalWickets,
        name: value.name,
        role: from_candid_PlayerRole_n16(_uploadFile, _downloadFile, value.role),
        totalRuns: value.totalRuns
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    country: string;
    matchCount: bigint;
    totalWickets: bigint;
    name: string;
    role: _PlayerRole;
    average: number;
    last5Performances: Array<_PerformanceSummary>;
    totalRuns: bigint;
    strikeRate: number;
}): {
    id: PlayerId;
    country: string;
    matchCount: bigint;
    totalWickets: bigint;
    name: string;
    role: PlayerRole;
    average: number;
    last5Performances: Array<PerformanceSummary>;
    totalRuns: bigint;
    strikeRate: number;
} {
    return {
        id: value.id,
        country: value.country,
        matchCount: value.matchCount,
        totalWickets: value.totalWickets,
        name: value.name,
        role: from_candid_PlayerRole_n16(_uploadFile, _downloadFile, value.role),
        average: value.average,
        last5Performances: value.last5Performances,
        totalRuns: value.totalRuns,
        strikeRate: value.strikeRate
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allRounder: null;
} | {
    batter: null;
} | {
    bowler: null;
}): PlayerRole {
    return "allRounder" in value ? PlayerRole.allRounder : "batter" in value ? PlayerRole.batter : "bowler" in value ? PlayerRole.bowler : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerSummary>): Array<PlayerSummary> {
    return value.map((x)=>from_candid_PlayerSummary_n14(_uploadFile, _downloadFile, x));
}
function to_candid_CreatePlayerInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePlayerInput): _CreatePlayerInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LeaderboardType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaderboardType): _LeaderboardType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): _PlayerRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdatePlayerInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePlayerInput): _UpdatePlayerInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country?: string;
    name?: string;
    role?: PlayerRole;
}): {
    country: [] | [string];
    name: [] | [string];
    role: [] | [_PlayerRole];
} {
    return {
        country: value.country ? candid_some(value.country) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        role: value.role ? candid_some(to_candid_PlayerRole_n5(_uploadFile, _downloadFile, value.role)) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    name: string;
    role: PlayerRole;
}): {
    country: string;
    name: string;
    role: _PlayerRole;
} {
    return {
        country: value.country,
        name: value.name,
        role: to_candid_PlayerRole_n5(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaderboardType): {
    runs: null;
} | {
    average: null;
} | {
    wickets: null;
} {
    return value == LeaderboardType.runs ? {
        runs: null
    } : value == LeaderboardType.average ? {
        average: null
    } : value == LeaderboardType.wickets ? {
        wickets: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): {
    allRounder: null;
} | {
    batter: null;
} | {
    bowler: null;
} {
    return value == PlayerRole.allRounder ? {
        allRounder: null
    } : value == PlayerRole.batter ? {
        batter: null
    } : value == PlayerRole.bowler ? {
        bowler: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
